# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  matrix:
    - PYTHON: "C:\\Python27"

    - PYTHON: "C:\\Python27-x64"

    - PYTHON: "C:\\Python34"

    - PYTHON: "C:\\Python34-x64"

    - PYTHON: "C:\\Python35"

    - PYTHON: "C:\\Python35-x64"

    - PYTHON: "C:\\Python36"

    - PYTHON: "C:\\Python36-x64"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;C:\MinGW\msys\1.0\bin;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install wheel"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/pytest"

after_test:
  - "%PYTHON%/python setup.py --command-packages wheel bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*
